apiVersion: v1
kind: Service
metadata:
  name: express-app-service
  labels:
    app: express-app
spec:
  selector:
    app: express-app-pod  
  ports:
    - protocol: TCP
      port: 80            
      targetPort: 3000    