apiVersion: apps/v1
kind: Deployment
metadata:
  name: express-app
  labels:
    app: express-app
spec:
  replicas: 2                    # number of pods (adjust as needed)
  selector:
    matchLabels:
      app: express-app-pod
  template:
    metadata:
      labels:
        app: express-app-pod
    spec:
      containers:
        - name: express-container
          image: secondthreadamit/my-first-repo:3
          ports:
            - containerPort: 3000
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "300m"
              memory: "256Mi"
          readinessProbe:           # checks if app is READY to receive traffic
            httpGet:
              path: /health
              port: 3000
            initialDelaySeconds: 3
            periodSeconds: 5
          livenessProbe:          
            httpGet:
              path: /health
              port: 3000
            initialDelaySeconds: 10
            periodSeconds: 10
